launcher:
    acceptUpdates: false
    buildNumber: 0
    channel: stable
    latestLWJGL: false
    loginRetries: 3
    memory: 0
    retryLogin: true
client:
    advancedOpenGL: 0
    anaglyph3D: false
    askBeforeOpeningUrl: true
    automateMode: 0
    automatePerformance: true
    autosave: 0
    betterGrass: 0
    brightnessSlider: 1.0
    buildNumber: 0
    channel: stable
    chatGrabsMouse: true
    chatOpacity: 0.5
    chatUsesRegex: false
    chunkRenderPasses: 1
    clearWater: false
    clientLight: false
    clearWater: false
    clipboardaccess: false
    delayedTooltips: false
    fancyBiomeColors: true
    fancyClouds: false
    fancyFog: true
    fancyGraphics: false
    fancyGrass: true
    fancyLight: false
    fancyParticles: true
    fancyTrees: false
    fancyWater: true
    fancyWeather: false
    farView: false
    fastDebug: 0
    fastLogin: false
    flightSpeedMultiplier: 1.0
    guiScale: 0
    highlightMentions: true
    hotbarQuickKeysEnabled: true
    ignorePeople: false
    mainMenuState: 1
    mipmapsPercent: 0.0
    performance: 0
    preloadedChunks: 0
    renderDistance: 2
    replaceBlocks: false
    replaceTools: false
    resizeScreenshots: false
    resizedScreenshotHeight: 3200
    resizedScreenshotWidth: 6000
    shaderType: 0
    showChatColors: true
    showDamageAlerts: true
    showJoinMessages: true
    signDistance: 8
    sky: true
    smoothFPS: false
    smoothLighting: 1 0
    stars: true
    time: 0
    viewBobbing: false
    voidFog: true
    waterBiomeColors: true
    weather: true
    worldbackup: false
